### Estudando a biblioteca Numpy
* Inicializando bibliotecas e parâmetros

In [545]:
import numpy as np
# Define 3 casas decimais e impede notação científica para números pequenos
np.set_printoptions(precision=3, suppress=True)

### 1. Criação de Arrays
O `ndarray` é o objeto central do NumPy. Ele permite armazenar dados de forma homogênea e eficiente.
* `np.array()`: Converte listas em arrays.
* `np.zeros()` / `np.ones()`: Cria matrizes preenchidas com 0 ou 1.
* `np.linspace()`: Cria sequências com intervalos calculados.

In [546]:
# Criando a partir de listas
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Arrays estruturados
zeros = np.zeros((2, 3)) 
espacado = np.linspace(0, 10, 5) # 5 números entre 0 e 10

print("Array 2D:\n", arr_2d)
print("Zeros:\n", zeros)
print("Linspace:", espacado)

Array 2D:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Linspace: [ 0.   2.5  5.   7.5 10. ]


### 2. Matemática Vetorizada
Diferente das listas, o NumPy permite operações aritméticas diretas sem a necessidade de loops `for`. Isso é conhecido como **vetorização**.

In [547]:
a = np.array([10, 20, 30, 40])
b = np.arange(4) # [0, 1, 2, 3]

print("Soma:", a + b)
print("Multiplicação por escalar:", a * 2)
print("Exponencial:", np.exp(b))
print("Seno:", np.sin(a))

Soma: [10 21 32 43]
Multiplicação por escalar: [20 40 60 80]
Exponencial: [ 1.     2.718  7.389 20.086]
Seno: [-0.544  0.913 -0.988  0.745]


### 3. Indexação e Filtros
Acessar dados no NumPy é potente: podemos usar intervalos, índices negativos ou até **máscaras booleanas** para filtrar valores.

In [548]:
matriz = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Slicing: [linhas, colunas]
# Pega as duas primeiras linhas e a última coluna
print("Matriz:\n",matriz)
print("Corte específico:\n", matriz[:2, -1])

# Filtro Booleano
mask = matriz > 50
print("Valores maiores que 50:", matriz[mask])

Matriz:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Corte específico:
 [30 60]
Valores maiores que 50: [60 70 80 90]


### 4. Manipulação de Formatos e Eixos
Muitas funções aceitam o argumento `axis`:
* `axis=0`: Operação ao longo das colunas (vertical).
* `axis=1`: Operação ao longo das linhas (horizontal).

In [549]:
arr = np.arange(12)
# Reorganiza para 3 linhas e 4 colunas
matriz_3x4 = arr.reshape(3, 4)

print("Matriz:\n", matriz_3x4)
print("Soma de cada coluna (Axis 0):", matriz_3x4.sum(axis=0))
print("Média de cada linha (Axis 1):", matriz_3x4.mean(axis=1))

Matriz:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Soma de cada coluna (Axis 0): [12 15 18 21]
Média de cada linha (Axis 1): [1.5 5.5 9.5]


### 5. Estatística e Aleatoriedade
O submódulo `random` é essencial para simulações e inicialização de pesos em modelos de IA.

In [550]:
# Gerando 5 números de uma distribuição normal
normal = np.random.randn(5)

# Métricas rápidas
print("Dados aleatórios:", (normal))
print("Ordem crescente:", np.sort(normal))
print(f"Desvio Padrão:, {np.std(normal):.3f}")
print(f"Variância:, {np.var(normal):.3f}")
print(f"Índice do valor máximo:, {np.argmax(normal):.3f}")
print(f"Valor máximo:, {np.max(normal):.3f}")
print(f"Valor mínimo:, {np.min(normal):.3f}")
print(f"Valor médio:, {np.mean(normal):.3f}")
print(f"Valor da mediana:, {np.median(normal):.3f}")

Dados aleatórios: [ 1.592 -1.214  0.114 -0.811  0.484]
Ordem crescente: [-1.214 -0.811  0.114  0.484  1.592]
Desvio Padrão:, 0.991
Variância:, 0.981
Índice do valor máximo:, 0.000
Valor máximo:, 1.592
Valor mínimo:, -1.214
Valor médio:, 0.033
Valor da mediana:, 0.114


### 6. Broadcasting
O **Broadcasting** é uma funcionalidade poderosa que permite ao NumPy realizar operações aritméticas entre arrays de diferentes formatos (shapes), desde que sejam compatíveis. O array menor é "transmitido" sobre o maior.

In [551]:
import numpy as np

# Um array 2D e um array 1D
matriz = np.array([[1, 2, 3], [4, 5, 6]])
vetor = np.array([10, 20, 30])

# O vetor é somado a cada linha da matriz automaticamente
resultado = matriz + vetor

print("Matriz (2x3):\n", matriz)
print("Vetor (1x3):", vetor)
print("Resultado do Broadcasting:\n", resultado)

Matriz (2x3):
 [[1 2 3]
 [4 5 6]]
Vetor (1x3): [10 20 30]
Resultado do Broadcasting:
 [[11 22 33]
 [14 25 36]]


### 7. Álgebra Linear
O NumPy é amplamente utilizado para cálculos matemáticos complexos. O submódulo `linalg` oferece ferramentas para resolver sistemas, calcular determinantes e muito mais.
* `np.dot()` ou `@`: Multiplicação de matrizes.
* `np.linalg.inv()`: Inversa de uma matriz.
* `np.linalg.det()`: Determinante.

In [552]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Multiplicação de matrizes (Diferente de A * B)
produto_matriz = np.dot(A, B) # Ou: A @ B

# Inversa e Determinante
inversa_A = np.linalg.inv(A)
determinante_A = np.linalg.det(A)

print("Matriz A:\n", A)
print("Matriz B:\n", B)
print("Produto Matricial:\n", produto_matriz)
print("Inversa:\n", inversa_A)
print(f"Determinante de A:, {determinante_A:.3f}")

Matriz A:
 [[1 2]
 [3 4]]
Matriz B:
 [[5 6]
 [7 8]]
Produto Matricial:
 [[19 22]
 [43 50]]
Inversa:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinante de A:, -2.000


### 8. Operações com Strings
O NumPy também possui um módulo específico (`char`) para manipular arrays de texto de forma vetorizada.

In [553]:
nomes = np.array(['python', 'numpy', 'jupyter'], dtype=str)

# Transformar em maiúsculas
maiusculo = np.char.upper(nomes)

# Adicionar sufixo
com_sufixo = np.char.add(nomes, '_dev')

# Adicionar prefixo
com_prefixo = np.char.add('pre_',nomes)

print("Original:", nomes)
print("Maiúsculo:", maiusculo)
print("Com Sufixo:", com_sufixo)
print("Com Prefixo:", com_prefixo)

Original: ['python' 'numpy' 'jupyter']
Maiúsculo: ['PYTHON' 'NUMPY' 'JUPYTER']
Com Sufixo: ['python_dev' 'numpy_dev' 'jupyter_dev']
Com Prefixo: ['pre_python' 'pre_numpy' 'pre_jupyter']


### 9. Tratamento de Dados Ausentes
Na ciência de dados, é comum encontrar valores nulos (`NaN` - Not a Number). O NumPy oferece funções específicas que ignoram esses valores em cálculos.

In [554]:
dados = np.array([1, 2, np.nan, 4, 5])

print("vetor:", dados)
print("Soma comum (retorna NaN):", np.sum(dados))
print("Soma ignorando NaN:", np.nansum(dados))
print("Média ignorando NaN:", np.nanmean(dados))

vetor: [ 1.  2. nan  4.  5.]
Soma comum (retorna NaN): nan
Soma ignorando NaN: 12.0
Média ignorando NaN: 3.0


### 10. Persistência de Dados
Você pode salvar seus arrays em arquivos binários compactos (`.npy`) ou arquivos de texto (`.txt`, `.csv`).

In [555]:
meus_dados = np.random.rand(5, 5)

# Salvar em formato binário NumPy
np.save('dados_projeto.npy', meus_dados)

# Carregar de volta
dados_carregados = np.load('dados_projeto.npy')

# Salvar como CSV simples
np.savetxt('dados.csv', meus_dados, delimiter=';', fmt='%.3f')

print("Dados salvos e carregados com sucesso!")

Dados salvos e carregados com sucesso!


### 11. Customização da Exibição
Por padrão, o NumPy pode exibir números muito pequenos em notação científica (ex: `7.64e-01`). Podemos configurar o notebook para mostrar apenas um número fixo de casas decimais e suprimir a notação científica para melhorar a legibilidade.

In [556]:
import numpy as np

# Criando dados similares aos da imagem (entre 0 e 1)
dados_exemplo = np.random.rand(5, 5)

# Configurando o NumPy:
# precision=3: Define 3 casas decimais
# suppress=True: Impede o uso de notação científica (e-01, etc)
np.set_printoptions(precision=3, suppress=True)

print("Dados formatados com 3 casas decimais:")
print(dados_exemplo)

# Para resetar as configurações para o padrão original, caso precise:
# np.set_printoptions(edgeitems=3, infstr='inf', linewidth=75, nanstr='nan', 
#                     precision=8, suppress=False, threshold=1000, formatter=None)

Dados formatados com 3 casas decimais:
[[0.435 0.952 0.212 0.213 0.213]
 [0.71  0.317 0.91  0.095 0.563]
 [0.33  0.007 0.682 0.18  0.87 ]
 [0.297 0.704 0.338 0.975 0.903]
 [0.052 0.601 0.935 0.34  0.577]]


### 12. Arredondamento Real
Diferente da configuração de exibição acima (que apenas muda como você **vê** o dado), as funções abaixo alteram os **valores reais** dentro do array.

In [557]:
# Criando um array com muitas casas decimais
arr_preciso = np.array([0.76490596, 0.85609321, 0.36945348])

# Arredondando para 3 casas
arr_arredondado = np.around(arr_preciso, decimals=3)

print("Original:", arr_preciso)
print("Arredondado de fato:", arr_arredondado)

Original: [0.765 0.856 0.369]
Arredondado de fato: [0.765 0.856 0.369]


### 13. Exportação com Precisão Definida
Ao salvar dados para ferramentas externas (como Excel), é comum querer controlar a precisão. 
O argumento `fmt='%.3f'` no `np.savetxt` garante que os dados sejam gravados com apenas 3 casas decimais e sem notação científica.

In [558]:
import numpy as np

# Gerando os dados
meus_dados = np.random.rand(5, 5)

# 1. Configura a exibição no console do Jupyter (não afeta o arquivo salvo)
np.set_printoptions(precision=3, suppress=True)

# 2. Salva em formato binário (mantém a precisão total para uso no Python)
np.save('dados_projeto.npy', meus_dados)

# 3. Salva como CSV formatado (perfeito para leitura humana e Excel)
# %.3f significa: número de ponto flutuante com 3 casas decimais
np.savetxt('dados.csv', meus_dados, delimiter=';', fmt='%.3f')

print("Dados exibidos no console com set_printoptions:")
print(meus_dados)
print("\nArquivo 'dados.csv' gerado com sucesso com 3 casas decimais!")

Dados exibidos no console com set_printoptions:
[[0.695 0.178 0.603 0.729 0.379]
 [0.379 0.521 0.841 0.956 0.009]
 [0.783 0.183 0.91  0.455 0.969]
 [0.744 0.815 0.029 0.703 0.292]
 [0.975 0.348 0.363 0.657 0.7  ]]

Arquivo 'dados.csv' gerado com sucesso com 3 casas decimais!
