### Estudando a biblioteca Numpy
* Inicializando bibliotecas e parâmetros

In [508]:
import numpy as np
# Define 3 casas decimais e impede notação científica para números pequenos
np.set_printoptions(precision=3, suppress=True)

### 1. Criação de Arrays
O `ndarray` é o objeto central do NumPy. Ele permite armazenar dados de forma homogênea e eficiente.
* `np.array()`: Converte listas em arrays.
* `np.zeros()` / `np.ones()`: Cria matrizes preenchidas com 0 ou 1.
* `np.linspace()`: Cria sequências com intervalos calculados.

In [509]:
# Criando a partir de listas
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Arrays estruturados
zeros = np.zeros((2, 3)) 
espacado = np.linspace(0, 10, 5) # 5 números entre 0 e 10

print("Array 2D:\n", arr_2d)
print("Zeros:\n", zeros)
print("Linspace:", espacado)

Array 2D:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Linspace: [ 0.   2.5  5.   7.5 10. ]


### 2. Matemática Vetorizada
Diferente das listas, o NumPy permite operações aritméticas diretas sem a necessidade de loops `for`. Isso é conhecido como **vetorização**.

In [510]:
a = np.array([10, 20, 30, 40])
b = np.arange(4) # [0, 1, 2, 3]

print("Soma:", a + b)
print("Multiplicação por escalar:", a * 2)
print("Exponencial:", np.exp(b))
print("Seno:", np.sin(a))

Soma: [10 21 32 43]
Multiplicação por escalar: [20 40 60 80]
Exponencial: [ 1.     2.718  7.389 20.086]
Seno: [-0.544  0.913 -0.988  0.745]


### 3. Indexação e Filtros
Acessar dados no NumPy é potente: podemos usar intervalos, índices negativos ou até **máscaras booleanas** para filtrar valores.

In [511]:
matriz = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Slicing: [linhas, colunas]
# Pega as duas primeiras linhas e a última coluna
print("Matriz:\n",matriz)
print("Corte específico:\n", matriz[:2, -1])

# Filtro Booleano
mask = matriz > 50
print("Valores maiores que 50:", matriz[mask])

Matriz:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Corte específico:
 [30 60]
Valores maiores que 50: [60 70 80 90]


### 4. Manipulação de Formatos e Eixos
Muitas funções aceitam o argumento `axis`:
* `axis=0`: Operação ao longo das colunas (vertical).
* `axis=1`: Operação ao longo das linhas (horizontal).

In [512]:
arr = np.arange(12)
# Reorganiza para 3 linhas e 4 colunas
matriz_3x4 = arr.reshape(3, 4)

print("Matriz:\n", matriz_3x4)
print("Soma de cada coluna (Axis 0):", matriz_3x4.sum(axis=0))
print("Média de cada linha (Axis 1):", matriz_3x4.mean(axis=1))

Matriz:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Soma de cada coluna (Axis 0): [12 15 18 21]
Média de cada linha (Axis 1): [1.5 5.5 9.5]


### 5. Estatística e Aleatoriedade
O submódulo `random` é essencial para simulações e inicialização de pesos em modelos de IA.

In [513]:
# Gerando 5 números de uma distribuição normal
normal = np.random.randn(5)

# Métricas rápidas
print("Dados aleatórios:", (normal))
print("Ordem crescente:", np.sort(normal))
print(f"Desvio Padrão:, {np.std(normal):.3f}")
print(f"Variância:, {np.var(normal):.3f}")
print(f"Índice do valor máximo:, {np.argmax(normal):.3f}")
print(f"Valor máximo:, {np.max(normal):.3f}")
print(f"Valor mínimo:, {np.min(normal):.3f}")
print(f"Valor médio:, {np.mean(normal):.3f}")
print(f"Valor da mediana:, {np.median(normal):.3f}")

Dados aleatórios: [-0.142  3.942  0.438 -0.169  1.723]
Ordem crescente: [-0.169 -0.142  0.438  1.723  3.942]
Desvio Padrão:, 1.552
Variância:, 2.408
Índice do valor máximo:, 1.000
Valor máximo:, 3.942
Valor mínimo:, -0.169
Valor médio:, 1.159
Valor da mediana:, 0.438


### 6. Broadcasting
O **Broadcasting** é uma funcionalidade poderosa que permite ao NumPy realizar operações aritméticas entre arrays de diferentes formatos (shapes), desde que sejam compatíveis. O array menor é "transmitido" sobre o maior.

In [514]:
import numpy as np

# Um array 2D e um array 1D
matriz = np.array([[1, 2, 3], [4, 5, 6]])
vetor = np.array([10, 20, 30])

# O vetor é somado a cada linha da matriz automaticamente
resultado = matriz + vetor

print("Matriz (2x3):\n", matriz)
print("Vetor (1x3):", vetor)
print("Resultado do Broadcasting:\n", resultado)

Matriz (2x3):
 [[1 2 3]
 [4 5 6]]
Vetor (1x3): [10 20 30]
Resultado do Broadcasting:
 [[11 22 33]
 [14 25 36]]


### 7. Álgebra Linear
O NumPy é amplamente utilizado para cálculos matemáticos complexos. O submódulo `linalg` oferece ferramentas para resolver sistemas, calcular determinantes e muito mais.
* `np.dot()` ou `@`: Multiplicação de matrizes.
* `np.linalg.inv()`: Inversa de uma matriz.
* `np.linalg.det()`: Determinante.

In [515]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Multiplicação de matrizes (Diferente de A * B)
produto_matriz = np.dot(A, B) # Ou: A @ B

# Inversa e Determinante
inversa_A = np.linalg.inv(A)
determinante_A = np.linalg.det(A)

print("Matriz A:\n", A)
print("Matriz B:\n", B)
print("Produto Matricial:\n", produto_matriz)
print("Inversa:\n", inversa_A)
print(f"Determinante de A:, {determinante_A:.3f}")

Matriz A:
 [[1 2]
 [3 4]]
Matriz B:
 [[5 6]
 [7 8]]
Produto Matricial:
 [[19 22]
 [43 50]]
Inversa:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinante de A:, -2.000


### 8. Operações com Strings
O NumPy também possui um módulo específico (`char`) para manipular arrays de texto de forma vetorizada.

In [516]:
nomes = np.array(['python', 'numpy', 'jupyter'], dtype=str)

# Transformar em maiúsculas
maiusculo = np.char.upper(nomes)

# Adicionar sufixo
com_sufixo = np.char.add(nomes, '_dev')

# Adicionar prefixo
com_prefixo = np.char.add('pre_',nomes)

print("Original:", nomes)
print("Maiúsculo:", maiusculo)
print("Com Sufixo:", com_sufixo)
print("Com Prefixo:", com_prefixo)

Original: ['python' 'numpy' 'jupyter']
Maiúsculo: ['PYTHON' 'NUMPY' 'JUPYTER']
Com Sufixo: ['python_dev' 'numpy_dev' 'jupyter_dev']
Com Prefixo: ['pre_python' 'pre_numpy' 'pre_jupyter']


### 9. Tratamento de Dados Ausentes
Na ciência de dados, é comum encontrar valores nulos (`NaN` - Not a Number). O NumPy oferece funções específicas que ignoram esses valores em cálculos.

In [517]:
dados = np.array([1, 2, np.nan, 4, 5])

print("vetor:", dados)
print("Soma comum (retorna NaN):", np.sum(dados))
print("Soma ignorando NaN:", np.nansum(dados))
print("Média ignorando NaN:", np.nanmean(dados))

vetor: [ 1.  2. nan  4.  5.]
Soma comum (retorna NaN): nan
Soma ignorando NaN: 12.0
Média ignorando NaN: 3.0


### 10. Persistência de Dados
Você pode salvar seus arrays em arquivos binários compactos (`.npy`) ou arquivos de texto (`.txt`, `.csv`).

In [519]:
meus_dados = np.random.rand(5, 5)

# Salvar em formato binário NumPy
np.save('dados_projeto.npy', meus_dados)

# Carregar de volta
dados_carregados = np.load('dados_projeto.npy')

# Salvar como CSV simples
np.savetxt('dados.csv', meus_dados, delimiter=';', fmt='%.3f')

print("Dados salvos e carregados com sucesso!")

Dados salvos e carregados com sucesso!
