### 1. Criação de Arrays
O `ndarray` é o objeto central do NumPy. Ele permite armazenar dados de forma homogênea e eficiente.
* `np.array()`: Converte listas em arrays.
* `np.zeros()` / `np.ones()`: Cria matrizes preenchidas com 0 ou 1.
* `np.linspace()`: Cria sequências com intervalos calculados.

In [3]:
import numpy as np

# Criando a partir de listas
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Arrays estruturados
zeros = np.zeros((2, 3)) 
espacado = np.linspace(0, 10, 5) # 5 números entre 0 e 10

print("Array 2D:\n", arr_2d)
print("Zeros:\n", zeros)
print("Linspace:", espacado)

Array 2D:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Linspace: [ 0.   2.5  5.   7.5 10. ]


### 2. Matemática Vetorizada
Diferente das listas, o NumPy permite operações aritméticas diretas sem a necessidade de loops `for`. Isso é conhecido como **vetorização**.

In [4]:
a = np.array([10, 20, 30, 40])
b = np.arange(4) # [0, 1, 2, 3]

print("Soma:", a + b)
print("Multiplicação por escalar:", a * 2)
print("Exponencial:", np.exp(b))
print("Seno:", np.sin(a))

Soma: [10 21 32 43]
Multiplicação por escalar: [20 40 60 80]
Exponencial: [ 1.          2.71828183  7.3890561  20.08553692]
Seno: [-0.54402111  0.91294525 -0.98803162  0.74511316]
